### ISSUE TITLE
Peer-review

### ISSUE THREAD

**Issue by UbdaNam** [MussieTeka/Awesome-Books#3]
**Highlight** 
You did a great job implementing the project according to the requirement 🥇 
➡️ Good use of GitHub flow
➡️ Use of Professional readme
➡️ Add book functionality works fine

##Center and decrease the top margin/padding on the main content.

Description:
When I click on the navigation menu, the content is not centered and has too much top margin. This causes an unsatisfactory user experience. Please center the content and reduce the top margin to make it easier for users to view the main content without scrolling. Thanks.

**Optional suggestion**
- Please consider decreasing the width of the main container.

**Comment by MussieTeka** [comment]
Hello @UbdaNam,

Thank you for raising the issue, and I have addressed them accordingly.

Best,
